language: python

cache:
  - pip
  - ccache

matrix:
  include:

    - name: "Ubuntu16.04 Py35 | chainer, chainermn, chainerx, docs"
      dist: xenial
      python: "3.5"
      env:
      - CHAINER_TRAVIS_TEST="chainer"
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - bash scripts/ci/travis/run-tests.sh before_install

install:
  - travis_wait bash scripts/ci/travis/run-tests.sh install

script:
  - bash scripts/ci/travis/run-tests.sh script

addons:
  apt:
    update: true
